@rem echo off
@echo 切换到UTF-8编码...
@chcp 65001  >/Nul
@echo 清空历史编译文件...
@nmake /NOLOGO clean >/Nul
@echo 编译静态库...
@nmake /NOLOGO >/Nul
@echo 编译调用静态库的程序...
@cl /nologo  /MD /Fe:main.exe call_add_2.c >/Nul
@echo 执行程序...
@main
