@rem echo off
@echo 切换到UTF-8编码...
@chcp 65001  >/Nul
@echo 编译调用动态库的程序...
@cl /c /utf-8 /nologo /MD /I "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.24.28314/include" /Fo:call_add.obj   call_add.c  >/Nul
@link /NOLOGO /OUT:main.exe /DYNAMICBASE Kernel32.lib call_add.obj  >/Nul
@echo 执行程序...
@main.exe
